//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cpe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cpe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var config = {
        ///    mode: &quot;fixed_servers&quot;,
        ///    rules: {
        ///        singleProxy: {
        ///            scheme: &quot;http&quot;,
        ///            host: &quot;{IP}&quot;,
        ///            port: parseInt({PORT})
        ///        },
        ///        bypassList: [{BYPASS_LIST}]
        ///    }
        ///};
        ///
        ///chrome.proxy.settings.set({
        ///    value: config,
        ///    scope: &quot;regular&quot;
        ///}, function () {});
        ///
        ///function callbackFn(details) {
        ///    return {
        ///        authCredentials: {
        ///            username: &quot;{CREDENTIALS_USER}&quot;,
        ///            password: &quot;{CREDENTIALS_PASS}&quot;
        ///        }
        ///    };
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string background {
            get {
                return ResourceManager.GetString("background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cpe128 {
            get {
                object obj = ResourceManager.GetObject("cpe128", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cpe16 {
            get {
                object obj = ResourceManager.GetObject("cpe16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cpe48 {
            get {
                object obj = ResourceManager.GetObject("cpe48", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information, call --help, -h..
        /// </summary>
        internal static string ForMoreInformationCallHelp {
            get {
                return ResourceManager.GetString("ForMoreInformationCallHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of available keys:.
        /// </summary>
        internal static string ListOfAvailableKeys {
            get {
                return ResourceManager.GetString("ListOfAvailableKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] manifest {
            get {
                object obj = ResourceManager.GetObject("manifest", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
